## ONLY DEVELOPERS
version: '3.9'

services:
  backend:
    image: ingeeduar/open-flow-cooworking:latest
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    container_name: openflow-backoffice
    ports:
      - "0.0.0.0:8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker

  postgres:
    image: postgis/postgis:15-3.5-alpine
    container_name: nelumbo_postgres
    restart: always
    environment:
      POSTGRES_DB: open_flow_coworking
      POSTGRES_USER: nelumbo
      POSTGRES_PASSWORD: 4LfTW6Om7u65qzOsvNpRZfRTqTioC
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - nelumbo_data:/var/lib/postgresql/data

volumes:
  nelumbo_data: {}