db:
  url: ${DB_URL}
  username: ${DB_USER}
  password: ${DB_PASS}
  pool:
    max-size: 15
    min-idle: 5

jpa:
  show-sql: false

notifications:
  url: ${NOTIFICATIONS_HOST}
  extraHeaders:
    - name: "Authorization"
      value: "xxxxxx"

security:
  jwt:
    secret: ${JWT_SECRET_KEY:E089Gtog9YaAsnp7pcsO6RV9phk2UgEVSfmWb5qHx+A=}
    expiration:
      value: ${JWT_EXPIRATION_VALUE:6}
      unit: ${JWT_EXPIRATION_UNIT:HOURS}
