server:
  address: 0.0.0.0
  port: 8080

spring:
  profiles:
    active: local

  web:
    resources:
      add-mappings: false
    error:
      whitelabel:
        enabled: false
      include-message: always
      
  application:
    name: open-flow-coworking

    security:
      jwt:
        secret-key: ${security.jwt.secret:arlhY+cHqLZgeFTc8XqHLvJ+RjGWDLDmzivVqHmS7/g=}
        expiration:
          value: ${security.jwt.expiration.value:6}
          unit: ${security.jwt.expiration.unit:HOURS}
          
    cors:
      allow-origin: ${cors.allow-origin:*}

  datasource:
    url: ${db.url:jdbc:postgresql://localhost:5432/postgres}
    username: ${db.username:postgres}
    password: ${db.password:postgres}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: ${db.pool.max-size:10}
      minimum-idle: ${db.pool.min-idle:2}
      idle-timeout: 30000
      pool-name: OpenFlowHikariCP

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: ${jpa.show-sql:false}

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
